sudo: required
services:
  - docker

before_install:
  - docker build -t georgexvii/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true georgexvii/react-test npm test -- --coverage

after_success:
  - docker build -t georgexvii/multi-client ./client
  - docker build -t georgexvii/multi-nginx ./nginx
  - docker build -t georgexvii/multi-server ./server
  - docker build -t georgexvii/multi-worker ./worker
